name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: yarn-c1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-c1-

      - uses: actions/setup-node@v2
        with:
          node-version: 14.17

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
