name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0
        with:
          install-command: yarn --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
