name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: BeeeQueue/setup-node@corepack
        with:
          corepack: true
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update release PR / Publish packages to `npm`
        id: changesets
        uses: changesets/action@master
        with:
          title: Release
          commit: Release new version
          publish: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
