name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: yarn-c1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-c1-

      - uses: actions/setup-node@v2
        with:
          node-version: 14.17

      - name: Install dependencies
        run: yarn install --immutable

      - name: Update release PR / Publish packages to `npm`
        id: changesets
        uses: changesets/action@master
        with:
          title: Release
          commit: Release new version
          publish: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
