name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0
        with:
          install-command: yarn --immutable

      - name: Update release PR / Publish packages to `npm`
        id: changesets
        uses: changesets/action@master
        with:
          title: Release
          commit: Release new version
          publish: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo '${{ toJSON(steps.changesets.outputs) }}'

      - name: Setup publish to GitHub Packages
        if: ${{ fromJSON(steps.changesets.outputs.published) == true }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Publish to GitHub Packages
        if: ${{ fromJSON(steps.changesets.outputs.published) == true }}
        run: npm publish --dry-run
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
